### ISSUE TITLE
Files with same names use namespace and can't be built

### ISSUE THREAD

**Issue by ssakhavi** [orbikm/mkdocs-ezlinks-plugin#18]
In Obsidian, if two files have the same name and are in different folders, the link will contain a slash. 
for example:
```
- folder1
+-- index.md
- folder2
+-- index.md
```
In Obsidian, the link for the first will be `[[folder1/index]]` and for the second it will be `[[folder2/index]]`. In other words: in order to distinguish between the files, it uses a namespace. There is a chance of having multiple layers of namespaces as well. 

A temporary workaround is to rename the files but I suggest that a fix. 

Thanks for the plugin btw.

**Comment by orbikm** [comment]
I had actually wanted to get this implemented, and would be relatively straightforward, if not a bit of work.

Your suggestion is reasonable, and I do want to get this functionality, and not just for obsidian links, this could work to disambiguate a number of duplicated filenames. I'll do some thinking on this and see what I can come up with. I'll be able to look into it this weekend, I'm sure.

Thanks for the issue report / feature request, and thanks for the kind words about the plugin as well!

**Comment by orbikm** [comment]
This feature has been merged in and released as `mkdocs-ezlinks-plugin==0.1.9`. Please give it a try, and let me know if this solution works for your needs. Also, please let me know if you run into any incorrect behavior using the new feature.

Thanks for using EzLinks!

**Comment by ssakhavi** [comment]
Thanks Mick. Will do.
