### ISSUE TITLE
Absolute links not using http:// or https:// are treated as relative

### ISSUE THREAD

**Issue by robbcrg** [orbikm/mkdocs-ezlinks-plugin#25]
In my case I am using IntelliJ and create links to allow me to edit any document from my editor using the Jetbrains Toolbox. The URL is of the form:

* `jetbrains://idea/navigate/reference?project=PROJECT-NAME&path=REALTIVE-PATH-TO-FILE:LINE-NUMBER
  * The LINE-NUMBER is optional

**Comment by orbikm** [comment]
This was fixed w/ PR #28. I will be putting together a release (0.12.0) which contains these fixes in just a few moments.

**Comment by orbikm** [comment]
Release is live, you should be able to  update using pip now to the latest.
