### ISSUE TITLE
Links between deeply nested subfolders fails

### ISSUE THREAD

**Issue by Mara-Li** [orbikm/mkdocs-ezlinks-plugin#35]
Hello. On my project, wikilinks doesn't seems to work.

My folder tree is : 

```
docs/
├─ assets/
│  ├─ img/
│  │  ├─ img_char1.png
├─ Roleplay/
│  ├─ characters/
│  │  ├─ char1.md
│  ├─ references/
│  │  ├─ ref char1.md
```
- All links pointing to `img` doesn't work
- All link from `char1` to `ref char1` doesn't work. 

Links is in a short path, as : `[[filename]]`

I have 404 error and the path pointed by links are : 
![image](https://user-images.githubusercontent.com/30244939/149517695-5ce02b77-886e-4a73-8cb1-67a25e036349.png)

After some try, it seems that after the 3rd folder, the links generations are broken. 

![image](https://user-images.githubusercontent.com/30244939/149518424-fe2a7804-60a3-4065-b476-f6d6fe78382c.png)

**Comment by orbikm** [comment]
I have reproduced your issue. I'm going to start investigating what is going on. Thank you for the report!

**Comment by Mara-Li** [comment]
Hello !
I'm happy to help you :D

I think it's possible to use `resolve` from [pathlib](https://docs.python.org/3/library/pathlib.html#pathlib.Path.resolve) or maybe something around `glob` all file ?

**Comment by orbikm** [comment]
Ok, this should be fixed now. Please pull down release 0.1.14 and let me know if this addresses it on your end. Feel free to re-open if the issue remains unresolved.

Once again, thanks for reporting the issue and using the plugin!

**Comment by Mara-Li** [comment]
It doesn't seems to be fixed, a last on my side : 
![image](https://user-images.githubusercontent.com/30244939/151217087-464b7dc5-2319-4258-ac17-3a9f53173987.png)
![image](https://user-images.githubusercontent.com/30244939/151217108-37c4a532-9e09-4b16-86da-1e6845a3099d.png)
![image](https://user-images.githubusercontent.com/30244939/151217141-8e4fa6a0-98fa-47d8-abf3-acaab65cc3e8.png)
![image](https://user-images.githubusercontent.com/30244939/151217160-527caafc-53cb-4821-9336-ed508de5b20a.png)

**Comment by Mara-Li** [comment]
It doesn't seems to work, on my side at last (windows 11) :
![image](https://user-images.githubusercontent.com/30244939/151218482-ce07de06-9fd6-4597-9bc8-e95b92cd9a27.png)
![image](https://user-images.githubusercontent.com/30244939/151218509-84451cfb-ac9d-4179-9aa8-5e5e1560885e.png)
![image](https://user-images.githubusercontent.com/30244939/151218539-0decdc49-feff-4ff4-93d2-2b1397014e22.png)

![image](https://user-images.githubusercontent.com/30244939/151218616-50895f3c-57bf-46a0-a3f0-73fadc7034d3.png)

Image are localized in `assets/img` who is in directly under docs (as `docs/assets/img`) and Mnémosyne folder is located in `docs/Roleplay/Personnages/Mnémosyne`
